apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: il-automation
  labels:
    environment: developer
    project: observability
    nx_cluster: G5
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: "admin@il-automation.local"
  PGADMIN_DEFAULT_PASSWORD: "adminpasswordsegura" # Modifícala por una segura
