apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: il-automation
  labels:
    environment: developer
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "tupasswordsegura" # Recuerda modificarla por una segura
  POSTGRES_DB: "mi_base_de_datos"
