---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: il-automation
  labels:
    environment: developer
    project: observability
    nx_cluster: G5
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: il-automation
  labels:
    environment: developer
    project: observability
    nx_cluster: G5
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        environment: developer
        project: observability
        nx_cluster: G5
    spec:
     containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "500m"
              memory: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
        labels:
          environment: developer
          project: observability
          nx_cluster: G5
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "nutanix-cluster-g5-volume"
        resources:
          requests:
            storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: il-automation
  labels:
    environment: developer
    project: observability
    nx_cluster: G5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: postgres # Nota: Mantiene conectividad interna con la app
        app-pgadmin: pgadmin
        environment: developer
        project: observability
        nx_cluster: G5
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - secretRef:
                name: pgadmin-secret
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "200m"
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: il-automation
  labels:
    environment: developer
    project: observability
    nx_cluster: G5
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app-pgadmin: pgadmin
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin-ingress
  namespace: il-automation
  labels:
    environment: developer
    project: observability
    nx_cluster: G5
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pgadmin-dev.illuminati.dark`)
      kind: Rule
      services:
        - name: pgadmin-service
          port: 80
  tls:
    secretName: wildcard-illuminati-tls
