apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nutanix-volume-g5
provisioner: csi.nutanix.com
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  storageContainer: "K8S_Storage"
  storageType: NutanixVolumes
  flashMode: ENABLED
  # Secret creado en el paso anterior
  csi.storage.k8s.io/provisioner-secret-name: ntnx-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ntnx-system
  csi.storage.k8s.io/node-publish-secret-name: ntnx-secret
  csi.storage.k8s.io/node-publish-secret-namespace: ntnx-system
  csi.storage.k8s.io/controller-expand-secret-name: ntnx-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ntnx-system
