apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elastic-nutanix-ssd
provisioner: csi.nutanix.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  # Reemplaza 'K8S_Storage' por el nombre real en tu Prism Element
  storageContainer: K8S_Storage
  # Fuerza el uso de rendimiento SSD en la cabina Nutanix
  flashMode: "true" 
  storageType: NutanixVolumes
