apiVersion: v1
kind: Secret
metadata:
  name: ntnx-secret
  namespace: ntnx-system
type: Opaque
stringData:
  # Reemplaza con los datos reales de tu entorno Nutanix
  key: PRISM_IP:9440
  flashMode: "true"
  username: TU_USUARIO
  password: TU_CONTRASEÑA
