apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: illuminati-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: "Illuminati Root CA"
  secretName: illuminati-root-ca-secret
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: illuminati-ca-issuer
spec:
  ca:
    secretName: illuminati-root-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-illuminati-tls
  namespace: default
spec:
  secretName: wildcard-illuminati-tls
  duration: 8760h # 1 año
  renewBefore: 720h # 30 días antes
  subject:
    organizations:
      - Illuminati IT
  commonName: "*.illuminati.dark"
  dnsNames:
    - "*.illuminati.dark"
    - "illuminati.dark"
    - "elasticsearch"
    - "elasticsearch.default.svc.cluster.local"
  issuerRef:
    name: illuminati-ca-issuer
    kind: ClusterIssuer
