apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: il-observability
  labels:
    environment: developer
    project: observability
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: admin-password
            - name: GF_DATABASE_TYPE
              value: postgres
            - name: GF_DATABASE_HOST
              value: "postgres-service.il-automation.svc.cluster.local:5432"
            - name: GF_DATABASE_NAME
              value: "grafana"
            - name: GF_DATABASE_USER
              value: "postgres"
            - name: GF_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: db-password
            - name: GF_DATABASE_SSL_MODE
              value: "disable"
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: il-observability
  labels:
    environment: developer
    project: observability
    app: grafana
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: grafana
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: il-observability
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana-dev.illuminati.dark`)
      kind: Rule
      services:
        - name: grafana-service
          port: 3000
  tls:
    secretName: wildcard-illuminati-tls 
