apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: il-observability
type: Opaque
stringData:
  admin-user: "admin"
  admin-password: "tu_password_seguro_para_grafana"
  db-password: "tu_password_de_postgres"
