apiVersion: v1
kind: Secret
metadata:
  name: ntnx-g5-secret
  namespace: ntnx-system
type: Opaque
stringData:
  key: "IP:9440:Nutanix_storage:password"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nutanix-cluster-g5-volume
provisioner: csi.nutanix.com
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  storageContainer: "K8S_Storage"
  storageType: NutanixVolumes
  # Secretos para aprovisionamiento
  csi.storage.k8s.io/provisioner-secret-name: ntnx-g5-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ntnx-system
  # Secretos para la fase de Attach/ControllerPublish (Faltaban estos dos)
  csi.storage.k8s.io/controller-publish-secret-name: ntnx-g5-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: ntnx-system
  # Secretos para la fase de NodePublish/Mount
  csi.storage.k8s.io/node-publish-secret-name: ntnx-g5-secret
  csi.storage.k8s.io/node-publish-secret-namespace: ntnx-system
  # Secretos para expansión
  csi.storage.k8s.io/controller-expand-secret-name: ntnx-g5-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ntnx-system
