apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: il-automation
  labels:
    environment: developer
    project: observability
type: Opaque
stringData:
  db-password: "password"
  encryption-key: "clave-secreta-muy-segura-para-n8n"
